<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-13 23:00

import django.db.models.deletion
=======
# Generated by Django 5.0.3 on 2024-03-13 22:39

>>>>>>> f6982b75a34259e05bd18976f6308f27a50a84c6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('geral', '0002_mecanico'),
=======
>>>>>>> f6982b75a34259e05bd18976f6308f27a50a84c6
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
<<<<<<< HEAD
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, verbose_name=' Valor R$')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='comissão R$')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.oficina', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
=======
                ('descrucao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor R$')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Comissão R$')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
>>>>>>> f6982b75a34259e05bd18976f6308f27a50a84c6
                'ordering': ['nome'],
            },
        ),
    ]
